theme: jekyll-theme-minimal
title: Dr. Gerard Alonso
logo: /Assets/Profile.png  # Algunos temas usan esto para poner tu foto en la barra lateral
description: I am an Assistant Professor in the Applied Molecular Thermodynamics Group. My research focuses on DFT, molecular simulation and thermodynamic modeling of phase equilibria and materials discovery.<br><br>
  <strong>Contact Information:</strong><br>
  📧 <a href="mailto:geraralonso@udec.cl">geraralonso@udec.cl</a><br>
  🏢 Office 407, Chemical Engineering Dept. Universidad de Concepción<br>
  🎓 <a href="https://scholar.google.com/citations?user=Yvt84FAAAAAJ">Google Scholar</a><br>
  💻 <a href="https://github.com/Gerard-Alonso">GitHub Profile</a>


# Información Personal y Académica
position: "Assistant Professor"
university: "Universidad de Concepción"
department: "Chemical Engineering Department"

# Líneas de Investigación (Research Interests)
research_interests:
  - "Molecular simulation of fluids and materials"
  - "Phase equilibrium thermodynamics"
  - "Computational Modeling of Adsorption in porous materials"

# Información de Contacto
contact_info:
  email: "geraralonso@udec.cl"
  office: "Facultad de Ingeniería, Departamento de Ingeniería Química, Oficina 407"
  google_scholar: "https://scholar.google.com/citations?user=Yvt84FAAAAAJ&hl=es"
  github_username: "Gerard-Alonso"
